[package]
name = "noa_languages"
version = "0.0.0"
authors = ["Seiya Nuta <nuta@seiya.me>"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
log = "0"
tree-sitter = "0"
ropey = "^1.3.2"

[build-dependencies]
cc = "*"
